name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22.2"

      - name: Install dependencies and run tests for database
        working-directory: database
        run: |
          go mod download
          go mod tidy
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env.test
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env.test
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env.test
          go test -v ./...

      - name: Run database
        working-directory: database
        run: |
          echo "ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY}}" >> .env.development
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env.development
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env.development
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env.development
          nohup go run cmd/phost/main.go &
          echo $! > app.pid

      - name: Install dependencies and run tests for backend
        working-directory: backend
        run: |
          go mod download
          go mod tidy
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env.development
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env.development
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env.development
          go test -v ./...

      - name: Install dependencies and run tests for frontend
        working-directory: frontend
        run: |
          npm install
          npm test

      - name: Stop database
        working-directory: database
        run: |
          if [ -f app.pid ]; then
              PID=$(cat app.pid)
              echo "Stopping application with PID $PID"
              kill $PID  
              rm app.pid  
          else
              echo "PID file not found. Is the application running?"
          fi
