name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.22.2"

      - name: Install dependencies
        run: go mod download

      - name: Install dependencies
        run: go mod tidy

      - name: Create .env.test file
        run: |
          echo "DB_HOST=${{ secrets.PORT }}" >> .env.test
          echo "DB_PORT=${{ secrets.ENCRYPTION_KEY }}" >> .env.test

      - name: Run tests
        run: go test -v ./...
